### ISSUE TITLE
Not working with Wolfram Language 11.3 on Linux (Debian, CentOS)

### ISSUE THREAD

**Issue by Ludwiggle** [WolframResearch/WolframLanguageForJupyter#1]
Is it tested on LInux?
I tried on Debian 9 and the installation does not give me errors, indeed I can create a new jupyter notebook with the Wolfram Langue 11.3 and the kernel starts but I cannot evaluate any expression;  the terminal where I start jupyter tells me " Timeout waiting for kernel_info reply from" .
Thanks

**Comment by GarrettND** [comment]
It has been tested on Linux, but it's possible there are still issues for some distributions. We will take a look at that combination of Debian and 11.3 to see if we can fix the issue.

**Comment by arnoudbuzing** [comment]
version 12 is working on Linux:

![image](https://user-images.githubusercontent.com/3236874/51772564-e5e80880-20b1-11e9-9dfe-d8e255c272e7.png)

**Comment by Ludwiggle** [comment]
Ok now it "works", but what if you write two expressions in a cell like
2+2
3+3

? That does not return anything

**Comment by Ludwiggle** [comment]
Now as soon as I open a notebook the CPU goes 100%. It evaluates expressions but constantly on 100%

**Comment by Ludwiggle** [comment]
Still high CPU usage, not 100% anymore but much higher than Mathematica or command line interface.

**Comment by cc-wr** [comment]
@Ludwiggle is this okay to close? Have you encountered any further bugs?

**Comment by Ludwiggle** [comment]
Still very inefficient (Debian 9). At idle there are two processes related to the WolframKernel that takes around 10% of CPU usage each.

**Comment by Ludwiggle** [comment]
And still no autocompletion, there are much better alternatives than this (iwolfram,
 and JWLS)
