### ISSUE TITLE
There aren’t any releases here

### ISSUE THREAD

**Issue by OVGULIU** [WolframResearch/WolframLanguageForJupyter#10]
Hi:

There aren’t any releases here

**Comment by cc-wr** [comment]
Hi,

Thank you: a release should be posted soon.

**Comment by OVGULIU** [comment]
Hi,

Thanks a lot for your support in advance!

**Comment by szhorvat** [comment]
There are still no releases. That's not a problem for me, but the installation instructions should not point to the releases page then.

**Comment by cc-wr** [comment]
This should be resolved.
