### ISSUE TITLE
Copy/paste output

### ISSUE THREAD

**Issue by HugoPfister** [WolframResearch/WolframLanguageForJupyter#100]
Hi all,

Thank you for this cool piece of code, I was used to Mathematica but my Univ. licence expired so I adopted to this free solution. 

One thing I was doing was to use the FortranForm to then copy paste to other pieces of code (in Python, Fortran, C etc...). Unfortunately, since the output is Latex-ed, the output is an image which cannot be copied. Is there a way to "switch" from latex-ed to non-latex-ed output?

Cheers,
Hugo

**Comment by cc-wr** [comment]
@HugoPfister, are you looking for something like `ToString[yourResult, FortranForm]`?

**Comment by HugoPfister** [comment]
Exactly, thank you!
