### ISSUE TITLE
Can't configure for Anaconda Jupyter Windows 10

### ISSUE THREAD

**Issue by Ali99947** [WolframResearch/WolframLanguageForJupyter#11]
When I run ConfigureJupyter["Add"], I get the error ConfigureJupyter::notfound: Jupyter installation on Environment["PATH"] not found.

I have installed Anaconda 3 and Jupyter Notebook and Jupyter Lab came with it. So I don't know the installation directory.

What should I add in the JupyterBinary for ConfigureJupyter["Add","JupyterBinary"->"..."]?

**Comment by cc-wr** [comment]
I would be happy to help you with this issue.

Accordingly, can you provide some additional information:

- What are the details of your platform?

- What is the result of `Environment["PATH"]` in Wolframscript or Mathematica? WolframLanguageForJupyter relies on the environment variable `PATH` to auto-discover Jupyter, and sometimes those applications do not correctly inherit the values for `PATH`.

- What is the value of the environment variable `PATH` when evaluated in your system's shell? For example, on Mac or Linux, what is the result of running `echo $PATH`? Or on Windows, what is the result of running `echo %PATH%` in `cmd.exe`?

> What should I add in the JupyterBinary for ConfigureJupyter["Add","JupyterBinary"->"..."]?

The option `"JupyterBinary"` expects the complete path to the Jupyter binary. As an example, the complete path to the Jupyter binary is `"/anaconda2/bin/jupyter"` on my system.

**Comment by Ali99947** [comment]
Thank you, for your response. I got it working on my Anaconda Distribution using Configure["Add","JupyterBinary"->"C:\Users\<user>\Anaconda3\Scripts"].
