### ISSUE TITLE
Issues with Images and PIL 

### ISSUE THREAD

**Issue by msollami** [WolframResearch/WolframLanguageForJupyter#12]
I was running the basic examples in the documentation and hit this error:

```
~/anaconda3/envs/fastai/lib/python3.6/site-packages/wolframclient/serializers/normalizer/pil.py in <module>()
      4 
      5 from wolframclient.utils import six
----> 6 from wolframclient.utils.api import PIL
      7 
      8 

ImportError: cannot import name 'PIL'
```

![Clipboard - April 23, 2019 2_01 PM (1)](https://user-images.githubusercontent.com/1467556/57238819-4adbc480-6ff8-11e9-9bd3-c0605f47782d.png)

**Comment by cc-wr** [comment]
This issue is not relevant to this project.

Please create a new issue at `WolframResearch/WolframClientForPython` (see https://github.com/WolframResearch/WolframClientForPython).

**Comment by bacanua** [comment]
This shouldn't be closed - it's obviously a limitation of both projects, please don't be so dismissive!

**Comment by cc-wr** [comment]
@bacanua, it was not my intention to be dismissive. I am sorry for that impression.

The purpose of this project is to allow for the evaluation of Wolfram Language commands, in its native syntax, in Jupyter. The purpose of `WolframResearch/WolframClientForPython` is to integrate Wolfram Language functionality into Python, which can then of course be run in Jupyter as Python.

I thought the difference was significant enough to warrant closing this issue, and asking the original poster reopen it in `WolframResearch/WolframClientForPython`.
