### ISSUE TITLE
env: wolframscript: No such file or directory

### ISSUE THREAD

**Issue by 597405567** [WolframResearch/WolframLanguageForJupyter#133]
In the Mac env , after install the Wolfram by the command:git clone https://github.com/WolframResearch/WolframLanguageForJupyter.git and ./configure-jupyter.wls add , the command line gives a prompt: env: wolframscript: No such file or directory
How to solve this problem?

**Comment by mahdiaslanimk** [comment]
@597405567  You need to download and install `wolframscript` first

**Comment by cc-wr** [comment]
This issue seems to be resolved. Closing.
