### ISSUE TITLE
Is it possible to use this with the jupyter extension for VScode ?

### ISSUE THREAD

**Issue by userrand** [WolframResearch/WolframLanguageForJupyter#139]
Thank you for this nice product. Is it possible to use this with jupyter extension for VScode or to use a custom notebook API (I do not know how that works) ?

**Comment by JuanG970** [comment]
I don't know if this is still relevant, but it is possible. Here is how I did this:
1. Configure your Mathematica as states in the README of this repo
2. Install [Jupyter extension](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter)
3. Create a new notebook and when prompted select "Jupyter Kernel" and if step 1 was done correctly you will see something like this:
<img width="2529" alt="SCR-20230405-nals" src="https://user-images.githubusercontent.com/36969954/230207784-8ccde1d9-1382-4986-b7b0-c62eda3d0d6a.png">

**Comment by userrand** [comment]
> I don't know if this is still relevant, but it is possible. Here is how I did this:
> 
>     1. Configure your Mathematica as states in the README of this repo
> 
>     2. Install [Jupyter extension](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter)
> 
>     3. Create a new notebook and when prompted select "Jupyter Kernel" and if step 1 was done correctly you will see something like this:
> 
> 
> <img alt="SCR-20230405-nals" width="2000" src="https://user-images.githubusercontent.com/36969954/230207784-8ccde1d9-1382-4986-b7b0-c62eda3d0d6a.png">

Hi, thank you. I forgot I opened this and I already use it in VScode. Thank you for the effort of looking for an image and everything (:   :+1:
