### ISSUE TITLE
MissingIDFieldWarning

### ISSUE THREAD

**Issue by walkerjian** [WolframResearch/WolframLanguageForJupyter#146]
/Users/walkerjian/anaconda3/lib/python3.11/site-packages/nbformat/__init__.py:128: MissingIDFieldWarning: Code cell is missing an id field, this will become a hard error in future nbformat versions. You may want to use `normalize()` on your notebooks before validations (available since nbformat 5.1.4). Previous versions of nbformat are fixing this issue transparently, and will stop doing so in the future.
  validate(nb)

$Version
13.2.1 for Mac OS X x86 (64-bit) (January 27, 2023)

Plot3d[Sin[x*y],{x,-Pi,Pi},{y,-Pi,Pi}]

Output: same as input

validate_nb(model['content'])
ToExpression::sntx: Invalid syntax in or before "validate_nb(model['content'])".
                                                                    ^

**Comment by cc-wr** [comment]
If you create a new Wolfram Language Jupyter notebook, do you still get similar errors when you try evaluations?

**Comment by walkerjian** [comment]
working now, just needed a power cycle, perhaps? just tested it on two plot functions as described in the docs, will test some more. I will also test it with ChatGPT API:

'so tell me a story of a young maiden true

ToExpression::sntx: Invalid syntax in or before "'so tell me a story of a young maiden true".
                                                  ^

$FAILED

sigh, should have known, 'eh? ...

**Comment by walkerjian** [comment]
so this:
Plot3d[Sin[x*y], {x, -Pi, Pi}, {y, -Pi, Pi}]
didn't work
and this, did:
Plot3D[Sin[x*y], {x, -Pi, Pi}, {y, -Pi, Pi}]

some big D energy needed, my fault for copypasta ...
