### ISSUE TITLE
After a few minutes of use, it fails with "too may files open"

### ISSUE THREAD

**Issue by szhorvat** [WolframResearch/WolframLanguageForJupyter#15]
I am on macOS 10.14.5 (note that macOS has a lower limit for the number of open files than other OS).

After using this for a few minutes, the system fails like this:

![image](https://user-images.githubusercontent.com/1212871/57967469-9e86d000-795f-11e9-8b89-268d3a85f9c8.png)

This is consistently reproducible, and only happens with the Wolfram Language kernel (not with other jupyter kernels).

In the notebook, the symptom is

![image](https://user-images.githubusercontent.com/1212871/57967480-c4ac7000-795f-11e9-99fa-e75c4287798b.png)

If you are trying to reproduce this, I suggest doing it on macOS.  Just open a notebook, start a kernel, then evaluate a few trivial things from time to time. It should happen in at most 10 minutes (very likely much sooner than that). There need not be many evaluations (10-20 should be sufficient).

----

I am not able to use this tool in practice because of this problem.

**Comment by cc-wr** [comment]
I cannot reproduce this issue, but this a known problem for an earlier version of the project.

Are you using the latest version on GitHub? If you are not, is the issue resolved if you update and reinstall?

**Comment by szhorvat** [comment]
Of all the issues I filed, this is the most serious one. This is the only one which makes the system unusable.

As I said in my response to #17, I made sure that I was using the version published in this GitHub repo. Are you using the same?  Did you try it on macOS?  The problem _always_ happens, but sometimes it takes 3 minutes and sometimes 15. With Python 2.7 it happened more frequently. With 3.7, it also happens every time, but it takes longer.

**Comment by cc-wr** [comment]
> As I said in my response to #17, I made sure that I was using the version published in this GitHub repo. Are you using the same? Did you try it on macOS?

I am, and I am completely unable to reproduce this issue.

I will link a tag to a form of the upcoming internal updates: I would ask you to see if in that version, this issue persists.

**Comment by cc-wr** [comment]
See 3466d98.

**Comment by szhorvat** [comment]
Sadly, it still happens.

**Comment by cc-wr** [comment]
Is `ulimit -n` 256, or has it been set lower?

**Comment by szhorvat** [comment]
Yes, it's 256. I never changed such system settings.

**Comment by cc-wr** [comment]
It seems like this might have to be a bit trial and error.

If you are okay with that, you may want to try this commit: db072b4fd368f11ca3efce8a333c698e73192c45.

**Comment by szhorvat** [comment]
It seems that when using `jupyter notebook` (and not `jupyter lab`), this problem does not occur.

**Comment by cc-wr** [comment]
Ok, so the short-term solution for this problem is to just use the `jupyter notebook` invocation.

I have created a new issue for the problems that occur when `WolframLanguageForJupyter` is launched, indirectly, from JupyterLab. See #32.
