### ISSUE TITLE
Null outputs are shown and are rasterized

### ISSUE THREAD

**Issue by szhorvat** [WolframResearch/WolframLanguageForJupyter#16]
When the evaluation result is `Null`, no output cell should be shown.  Currently, an ugly rasterized `Null` is shown.

![image](https://user-images.githubusercontent.com/1212871/57967518-6469fe00-7960-11e9-926c-bfab9d102a1e.png)

**Comment by cc-wr** [comment]
This issue will be fixed when a pull request internal to Wolfram Research is merged.

**Comment by cc-wr** [comment]
I will close this issue for the moment. (If anybody objects, please say so.)

Once the internal pull request is merged, I will update this issue. This issue may also be reopened at that time.

Discussion on whether this is a sensible method of development is occurring here: #24.

**Comment by cc-wr** [comment]
This issue should be fixed in master.
