### ISSUE TITLE
Trace does not work

### ISSUE THREAD

**Issue by szhorvat** [WolframResearch/WolframLanguageForJupyter#19]
`Trace` does not seem to work. It always returns `{}`.

![image](https://user-images.githubusercontent.com/1212871/57988031-801cf380-7a89-11e9-866b-1ed3827767ab.png)

Code:

```mma
f[x_]:=x^2; Trace[f[3+4]]
```

I thought that this happens because we are always in some evaluation (this can e.g. be detected with `Stack[]`, which is not empty at the "top level"), but it's not clear why that would break Trace ...

`On[]` and `Off[]` also do not work, for tracing purposes.

![image](https://user-images.githubusercontent.com/1212871/57988049-c6725280-7a89-11e9-89d1-8e405decb74e.png)

Compare the command line:

```
In[1]:= f[x_]:=x^2; Trace[f[3+4]]                                               

                            2
Out[1]= {{3 + 4, 7}, f[7], 7 , 49}

In[2]:= On[]                                                                    

On::trace: On[] --> Null.

In[3]:= 3+4                                                                     

Plus::trace: 3 + 4 --> 7.

Out[3]= 7

In[4]:= Off[]                                                                   

In[5]:=         
```

**Comment by cc-wr** [comment]
The `WolframLanguageForJupyter` kernel is started by `WolframKernel` with the `-script` option.

This problem is inherent to that environment.

**Comment by cc-wr** [comment]
You should run into similar constraints with invocations like `./WolframKernel -run "Print[Trace[x=2+2]]"`.

**Comment by cc-wr** [comment]
It may be a good idea to try to launch the kernel script from `wolframscript` and `-file`, if they are available, since doing so will not cause this limitation.

**Comment by cc-wr** [comment]
There is an internal bug report for this limitation of the `-script` `WolframKernel` environment, and hopefully it will be fixed soon.

For now, I will close this issue: I will update it with any new information that appears.
