### ISSUE TITLE
Begin[] / End[] do not take effect within a single cell

### ISSUE THREAD

**Issue by szhorvat** [WolframResearch/WolframLanguageForJupyter#20]
Try evaluating the following in a single cell:

```mma
Begin["foo`"]
Context[xyz]
End[]
```

The expected output of `Context[xyz]` is ``foo` ``. This would be consistent with how the notebook interface and the command line interface work.

If we split the three lines across cells, then everything is fine.

![image](https://user-images.githubusercontent.com/1212871/57988436-a4c79a00-7a8e-11e9-9e40-c6ca6ac0454a.png)

**Comment by cc-wr** [comment]
Currently, as soon as a symbol is loaded into the kernel, even before the input line it is in has been evaluated, a context is imprinted on it. I imagine this the cause of this issue.

I will add a fix that loads an input line only after the previous input line has actually been evaluated.

**Comment by cc-wr** [comment]
You may want to check out 34084b057d8f4b366cd4132569dc360e5e2c0acb to see if it fixes this issue for you. (It does for me.)

**Comment by cc-wr** [comment]
> You may want to check out [34084b0](https://github.com/WolframResearch/WolframLanguageForJupyter/commit/34084b057d8f4b366cd4132569dc360e5e2c0acb) to see if it fixes this issue for you. (It does for me.)

See #46 now.

**Comment by cc-wr** [comment]
This should be resolved in `master`.
