### ISSUE TITLE
% causes infinite recursion

### ISSUE THREAD

**Issue by szhorvat** [WolframResearch/WolframLanguageForJupyter#24]
It is not possible to use `%` to refer to the last output.

![image](https://user-images.githubusercontent.com/1212871/58006919-690dee00-7ae9-11e9-84bf-a0b1cfa24e22.png)

**Comment by cc-wr** [comment]
These types of issues — i.e., relating to line contexts — will be fixed with an update to the GitHub repository from a pull request internal to Wolfram Research.

I am going to close this issue because another issue dealing with lines is already open.

**Comment by szhorvat** [comment]
Just a note on this getting closed:

We do not have access to the fix. The current impression is that this software is being developed behind closed doors and occasionally synced up with the public version. This is going to discourage people who thought about hacking on the project.

If I sent a PR, I expect that you wouldn't merge it because it would conflict with the internal version. I am also not keen on sending any since whatever I might implement could already be part of the internal version.

**Comment by cc-wr** [comment]
I am sorry that the current method of development discourages you from contributing yourself.

Do you feel that a pinned issue containing features being worked on for the next internal update to the project would alleviate this problem? Or do you think that having all internal work be made in this GitHub repository is the only way to go?

**Comment by szhorvat** [comment]
I think that people will only be encouraged to contribute if the impression is that a significant portion of changes are being published here quickly. Ideally, development is being done completely in the open. However, this is just a personal opinion / guess.

For more on this topic, it's better if you email me ...

**Comment by jfultz** [comment]
@szhorvat , in the sense in which you seem to define it, all software is being developed "behind closed doors".  When I do open source development on my machine and don't push it (e.g., it's not finished, it's not tested, it's experimental, it's embarrassing, it doesn't adhere to coding standards), that's not much different from what's being done here.

You seem to be concerned that Wolfram is going to do development and then sit on it from some period of time.  There's no reason for Wolfram to do that.  For paid software, it's a delicate dance...when Wolfram sits on finished development, it costs Wolfram money, opportunities, and reputation for not releasing it, but this is balanced by the fact that releases are expensive.  But for open source development on Github, all of the costs of delay remain, while the cost of releasing evaporates.

So, why would Wolfram handle pull requests offline?  Well, it allows us to benefit from the experience of internal reviewers who prefer not to have their every comment publicly scrutinized or who, for privacy reasons, just prefer not to have a Github profile at all.  The PR also shows up in our internal tracking which makes it less likely to get overlooked/forgotten as a review task (i.e., it can actually *speed things up*).

This isn't a company policy...we let the repo owners do what works best for them here.  But I'm the person who works with all of the repo owners to help them understand their options, and I respectfully disagree with @szhorvat that this option discourages open source development.

**Comment by szhorvat** [comment]
@jfultz  What I wrote above was meant in very practical terms (it was not meant as an expression of a software development philosophy). Also, as I said it is just an opinion. What _actually_ encourages/discourages people from contributing to this project remains to be seen. 

One reason I wrote it is that after I pointed out a number of issues, it was suggested to me (through a different channel) that since it is open source, users like me can contribute and fix it up.  Thus, I did consider digging into the code.  However, personally, I felt discouraged because it quickly became clear that there exists another, non-public version, which: (1) may already have the fixes or features I would have added (2) may be so different from the public version that porting over changes based on the public version may be too much work for the developer (and thus my contribution would get rejected, for very practical reasons). The internal version was posted today and indeed it is _very_ different ... it's not simply a few commits ahead.

This is of course just one person's reaction. I hope that sharing it can be of some use, but make of it what you will. Others may react differently. This is why I said, "However, this is just a personal opinion / guess".  It was meant as constructive criticism through showing how an outsider may perceive the project.

What I did not spell out—perhaps I should have—is that I know that many of us appreciate that WRI is opening up projects. Thank you! Criticism is given with the sole intent to improve things, and help get the most out of open repositories.

I think that at this point the discussion may have gone too much ahead of itself to be able to focus on practically relevant things. The most immediate issue is that this tool should work reasonably well. In the meantime, @cc-wr and I discovered that my bad experiences were mainly due to using `jupyter lab` instead of `jupyter notebook`. With `jupyter notebook`, the first impression is much better (at least when using the internal version).

**Comment by jfultz** [comment]
@szhorvat, to be clear, there are not multiple versions of the master branch.  If your source led you to believe otherwise, that's simply wrong.  The master branch in Github is *exactly* the master branch in our repo (I just moments ago verified this...same SHA).  The master branch contains all finished development, so in that sense, there is only one version (but, as I said, we're fielding internal pull requests on a private server...but until it's merged, we consider that *unfinished* development).

One issue you raise indirectly comes up elsewhere in open source, which is multiple people taking on an open issue, and then some parties feeling like their work is wasted.  Yup...that's a problem, but not just when one of the parties is Wolfram.  But I think the repo owner adding a "fix incoming" label is a good way to telegraph what we're working on.

And yes, to be clear, we're all friends here, and I hope that my comments are understood as being fully respectful (while in partial disagreement with some specific points).  This repo in general is very exciting because, while it's not the most popular repo Wolfram has published (that would be the Arrival livestream repo), it is by far the most active (in terms of issue reporting, PRs, etc.).

**Comment by cc-wr** [comment]
This issue should now be fixed in master.
