### ISSUE TITLE
More graceful failure needed when licenses are exhausted

### ISSUE THREAD

**Issue by szhorvat** [WolframResearch/WolframLanguageForJupyter#25]
I have `$MaxLicenseProcesses == 2`. If I open a 3rd notebook, it just doesn't work, but there is no indication why. 

I do see some messages like this in the terminal, but it's still not clear what is happening:

![image](https://user-images.githubusercontent.com/1212871/58007184-023d0480-7aea-11e9-83d0-93b38b979367.png)

Many users will simply assume that the system is broken when this happens. It will not occur to them that they exhausted their licenses. Some more graceful failure mode (e.g. a descriptive error message) would be useful.

**Comment by cc-wr** [comment]
Well, to an extent, it is difficult for WolframLanguageForJupyter to do anything specific, exactly because its licenses are exhausted — an unfortunate side-effect of having the project built natively in the Wolfram Language.

**Comment by cc-wr** [comment]
I don't see an immediate fix to this issue. Am I overlooking something here?

If this is an existential problem for this project as it currently stands, I am going to close this issue.

**Comment by szhorvat** [comment]
I think the `wontfix` is reasonable here. 

But it would be useful to improve the Wolfram kernel itself to behave better when licenses are exhausted. If I start it in command line mode, it simply prints the usual header, then exits without a word. Maybe it could print a message about why it exits (not enough licenses), then that message can be captured and identified.
