### ISSUE TITLE
?context`* does not work

### ISSUE THREAD

**Issue by szhorvat** [WolframResearch/WolframLanguageForJupyter#26]
Evaluating 

```
?someContext`*
```

returns with pink boxes.

Example:

![image](https://user-images.githubusercontent.com/1212871/58038599-98941900-7b30-11e9-8727-ffdbb9afbd73.png)

**Comment by cc-wr** [comment]
This issue should now be fixed in `master`.

**Comment by cc-wr** [comment]
This command requires the frontend, so to handle it, a `UsingFrontEnd` wrapper needed to be added.
