### ISSUE TITLE
Jupyter interaction code pollutes the Global namespace

### ISSUE THREAD

**Issue by szhorvat** [WolframResearch/WolframLanguageForJupyter#27]
When starting up, the Global context should be empty.

We cannot test this using

    ?Global`*

because of #26, but we can use `Names`. It reveals that the Global namespace is not empty.

![image](https://user-images.githubusercontent.com/1212871/58038649-cf6a2f00-7b30-11e9-9b3c-cd62c82209c9.png)

On a related note, `$ContextPath` should also be pristine.  The ZeroMQLink package should be loaded without permanently modifying the context path.

**Comment by cc-wr** [comment]
This issue should now be fixed in `master`.

**Comment by szhorvat** [comment]
After all the fixes you made on master, do you recommend I switch back from `internal-one` to the master branch?

**Comment by cc-wr** [comment]
`master` currently is basically `internal-one`, just updated with the fixes from two pull requests (#13, #18), so it wouldn't hurt to switch back (to `master`).

**Comment by cc-wr** [comment]
I have deleted the tags `internal-one` and `internal-two`.
