### ISSUE TITLE
ConfigureJupyter["Add"] doesn't work correctly on Linux

### ISSUE THREAD

**Issue by halirutan** [WolframResearch/WolframLanguageForJupyter#28]
When running `ConfigureJupyter["Add"]` on Linux without further arguments, it returns a message that the WolframKernel binary cannot be found. This issue originates most likely in the following condition branch

https://github.com/WolframResearch/WolframLanguageForJupyter/blob/b70e8f5cdc23984d0aeb37729ea8fda30f35cd5b/WolframLanguageForJupyter/WolframLanguageForJupyter.m#L96-L97

For Linux, which is `"Unix"` this returns a wrong path.

**Comment by cc-wr** [comment]
Does #30 fix this for you?

**Comment by halirutan** [comment]
@cc-wr This should work, but why not simplify this whole section and use

> ![img](http://i.stack.imgur.com/phKtw.png)

I tested this on Linux and OSX and it works both in Mathematica and with `wolframscript`.

**Comment by cc-wr** [comment]
@halirutan, that section was intentional. `First[$CommandLine]` can be relative.

For example, what if I have `WolframKernel` on `PATH`, and I run just `WolframKernel` in a terminal. `$CommandLine` will evaluate to `{WolframKernel}`, and this will lead to a bad entry in Jupyter if, say, `ConfigureJupyter["add"]` is used.

**Comment by halirutan** [comment]
It's still working on Linux, but you might be right for other operating systems. Here, for instance, I have everything on the `PATH` and it's still resolved

```
patrick@lupus:~$ wolframscript -c 'First[$CommandLine]'
/usr/local/Wolfram/Mathematica/12.0/SystemFiles/Kernel/Binaries/Linux-x86-64/WolframKernel
```

**Comment by cc-wr** [comment]
`wolframscript` knows the absolute path of `WolframKernel`, and starts it with such.

To try my example, make sure your `WolframKernel` is on `PATH`, run `WolframKernel` itself, and then check the value of `$CommandLine`.

**Comment by halirutan** [comment]
I'm in my home directory. `WolframKernel` is under `/usr/local/...` but on the path:

![img](http://i.imgur.com/Hikhb4A.png)

**Comment by cc-wr** [comment]
> To re-iterate: I don't want to argue with you because it is entirely possible that something like this happens on other systems. And it's better to be safe than sorry.

I am surprised that it is being rewritten on Linux, but yeah, I am pretty sure that it can happen easily on macOS.

**Comment by cc-wr** [comment]
If you are interested in why this occurs on Linux, I looked into it for a moment, and I imagine the `WolframKernel` you are invoking is symlinked to the ".../Executables/WolframKernel" binary. This binary, however, calls another `WolframKernel` (the ".../SystemFiles/Kernel/Binaries/...") version with its absolute path, according to my understanding.

So it is much easier to get caught up in `WolframKernel` indirection on Linux, making it more likely that you will get an absolute path for `First[$CommandLine]`.
