### ISSUE TITLE
Short does not work

### ISSUE THREAD

**Issue by szhorvat** [WolframResearch/WolframLanguageForJupyter#31]
`Short` has no effect.  Using `jupyter notebook` this time, internal build from https://github.com/WolframResearch/WolframLanguageForJupyter/releases/tag/internal-one

![image](https://user-images.githubusercontent.com/1212871/58104363-f8e49280-7be4-11e9-925f-a56d48c02a13.png)

**Comment by cc-wr** [comment]
> internal build from https://github.com/WolframResearch/WolframLanguageForJupyter/releases/tag/internal-one

Note: This is now just `master`.

**Comment by Ludwiggle** [comment]
I don't understand why this project is so buggy while you have something like https://github.com/mmatera/iwolfram that works really well. Just fork it.

**Comment by cc-wr** [comment]
Having alternatives never hurt anyone.

**Comment by Ludwiggle** [comment]
Sure! :)
But let me elaborate my doubts. I also created an jupyter kernel for the Wolfram language which works just fine for my needs. My version is a modified bash_kernel which pipes wl expression in fifo's, extremely  simple. It is even slimmer than the original bash_kernel, which is already pretty minimal. IWolfram is a bit more complex cause it relies on IPython, but still, it's way more concise than WolframLanguageForJupyter. 
So, my doubt is that maybe this project is buggy cause it is overly complex without providing any superior functionalities compare to its rivals.
I hope you will prove me wrong.

Thanks

**Comment by cc-wr** [comment]
@Ludwiggle, I also hope that this project eventually meets your requirements.

**Comment by cc-wr** [comment]
`Short` uses the `PageWidth` setting of `$Output`, so it should be simple enough to fix this issue by setting that `PageWidth` to a smaller value.

**Comment by cc-wr** [comment]
This should be resolved.
