### ISSUE TITLE
Starting WolframLanguageForJupyter with JupyterLab can cause mysterious behaviour

### ISSUE THREAD

**Issue by cc-wr** [WolframResearch/WolframLanguageForJupyter#32]
For example, a "Too may files open" error may be quickly given (see #15), or `In[*]` may not resolve to an index (see #14).

**Comment by cc-wr** [comment]
I can reproduce on macOS.

**Comment by jbulow** [comment]
I can reproduce on Ubuntu 18.04.

This might be related: https://github.com/jupyter/notebook/issues/3748

**Comment by msollami** [comment]
I've seen this as well in macOS 10.14.5 and from within native jupyter's Nteract.

**Comment by szhorvat** [comment]
@cc-wr Did you manage to figure out why this is failing? It would be so useful to be able to use the modern "lab" interface.

**Comment by cc-wr** [comment]
@szhorvat, how much of this issue does a0870db7be9f0552bce6a6bee44d117972fa8e47 resolve for you (if at all)?

**Comment by szhorvat** [comment]
I'll be away for a few days, I'll be able to check on the weekend. Thanks for trying to fix this!

**Comment by cc-wr** [comment]
A review for this will be created soon for merging this into `master`.

**Comment by cc-wr** [comment]
The pull request for this should be in `master`.

(No request for comments was made for this fix, but they will be present for future pull requests.)
