### ISSUE TITLE
Sometimes % does not work properly

### ISSUE THREAD

**Issue by rsato64** [WolframResearch/WolframLanguageForJupyter#42]
When I put % to get the result from the previous line in the same box, it does not work properly.

![Selection_043](https://user-images.githubusercontent.com/39657408/58966846-5404b080-87b3-11e9-9e6d-2c80e5dc438c.png)

**Comment by cc-wr** [comment]
Does this commit 34084b057d8f4b366cd4132569dc360e5e2c0acb resolve the issue for you?

**Comment by rsato64** [comment]
Now the issue is solved. Thanks!

**Comment by cc-wr** [comment]
The pull request for this is #46.

**Comment by cc-wr** [comment]
This should be resolved in `master`.
