### ISSUE TITLE
No output if the number of terms is too large

### ISSUE THREAD

**Issue by vsht** [WolframResearch/WolframLanguageForJupyter#43]
It seems that `toOutText` can handle only a limited number of terms.
While this works
```
Sum[c[i],{i,1,5984}]
```
the following
```
Sum[c[i],{i,1,5985}]
```
returns `$Failed`. The expression is correctly processed by the kernel, it is just that the notebook interface cannot show that many terms. As a workaround I would suggest using `Shallow` since e.g. 
```
Shallow[Sum[c[i],{i,1,10000}]]
```
evaluates just fine. 

I'm using the latest master branch version of WolframLanguageForJupyter with the Free Wolfram Engine 12.0.0 for Linux (May 19, 2019) on Fedora 29.

**Comment by cc-wr** [comment]
Is the problem resolved if you try the pull request #53?

**Comment by vsht** [comment]
Yes, with the `bugfix/rasterization-failure` branch the problem seems to be gone.

**Comment by cc-wr** [comment]
A review for this will be created soon for merging this into `master`.

**Comment by cc-wr** [comment]
The pull request for this should be in `master`.

(No request for comments was made for this fix, but they will be present for future pull requests.)
