### ISSUE TITLE
Request For Comments: Make common idioms for setting a persistent format type for output effective

### ISSUE THREAD

**Issue by cc-wr** [WolframResearch/WolframLanguageForJupyter#48]
This a "Request For Comments/Consensus"-type issue for the pull request #46.

#46 makes changes to assure that, to an extent, the following common idioms for setting a persistent format type (see also #45) work:

* `SetOptions[$Output, FormatType -> TraditionalForm]`
* `$Post=TraditionalForm`
* `$PrePrint=TraditionalForm`
* `CurrentValue[$FrontEndSession, {CommonDefaultFormatTypes, "Output"}] = TraditionalForm`

(After #46, this last command only applies to outputs that would have been rasterized by the Front End before `TraditionalForm` was applied.)

Some of these changes involve the implementation of various standard hooks in the `WolframLanguageForJupyter` evaluation loop (see also #47).

The hooks implemented, in the attached pull request, are:

* `$PreRead`
* `$Pre`
* `$Post`
* `$PrePrint`

---

Any relevant comments (e.g., support, complaints, objections, suggested improvements) are welcome.

It may also be helpful if you provide something like the following in your comment:

> * +2 : I am happy with this proposal, and I will argue for it
> * +1 : I am happy with this proposal, but will not argue for it
> * 0 : I have no opinion
> * -1 : I am not happy with this proposal, but will not argue against it
> * -2 : I am not happy with this proposal, and I will argue against it

https://xenproject.org/developers/governance/#expressingopinion

**Comment by cc-wr** [comment]
This request ends in one week from now.

**Comment by cc-wr** [comment]
Since no comments were registered, I will go ahead and merge #46.

**Comment by vipa7070** [comment]
I'm sorry I don't speak English very well and I don't understand very well how this web site work but I think that the issue in the exponent should have been solved, therefore:
+2 : I am happy with this proposal.
