### ISSUE TITLE
Kernel restarts and then dies on OSX

### ISSUE THREAD

**Issue by ziofil** [WolframResearch/WolframLanguageForJupyter#54]
I tried on jupyter notebook and jupyter-lab, same behaviour. 
I can create a new notebook with the Wolfram kernel, and as soon as I run any code, even `1+1`, I get the console message

    KernelRestarter: restarting kernel (1/5), new random ports
    KernelRestarter: restarting kernel (2/5), new random ports
    KernelRestarter: restarting kernel (3/5), new random ports
    KernelRestarter: restarting kernel (4/5), new random ports

and then

    KernelRestarter: restart failed
    Kernel e7228dc3-4af3-43b6-9685-fe458ef46660 died, removing from map.

**Comment by cc-wr** [comment]
Hello,

To help diagnose this issue, can you provide some additional information? See below.

---
**What is the platform?**

**What is the version of the Wolfram Language you are using?**

**How did you install `WolframLanguageForJupyter`?**

**What is outputted when you run `jupyter kernelspec list` in `Terminal`?**

It should look something like this:

```
Available kernels:
  wolframlanguage12    /Users/cc-wr/Library/Jupyter/kernels/wolframlanguage12
  python3              /Users/cc-wr/anaconda3/share/jupyter/kernels/python3
```

If the output does look like the above, the directory to the right of `wolframlanguage12` should contain a file called `kernel.json`. What are the contents of that file?

For example, to get the contents of my `kernel.json` file, I could run something like the following in `Terminal`:

```
cat /Users/cc-wr/Library/Jupyter/kernels/wolframlanguage12/kernel.json
```

**Comment by ziofil** [comment]
Hi, thanks for replying. For some reason, now it has started working on its own.
I'm closing the issue, I'll reopen it if the problem represents itself.

**Comment by ecbrown** [comment]
I see that the matter is closed, but this has happened for me with the same symptoms when I have gone over the license limit.
