### ISSUE TITLE
Atom hydrogen Mathematica language mapping

### ISSUE THREAD

**Issue by paulps2** [WolframResearch/WolframLanguageForJupyter#55]
I'm not sure whether this problem is related within this repository. I would like to use atom hydrogen for programming wolfram language. However, the following error occurs
`No kernel for grammar Mathematica found`
My guess is that atom recognized the code in my .wl file automatically as `Mathematica`, but the kernel for Jupyter is called `Wolfram Language`. I found that in hydrogen, language mappings can be set addressing this problem. I tried different versions but none of them worked
```
{ "wolfram language 12": "Mathematica" }
{ "wolframlanguage12": "mathematica" }
{ "Wolfram Language 12": "Mathematica" }
```

`jupyter kernelspec list` shows that the kernel is installed properly.

```
Available kernels:
  ir                   /Users/Peezy/Library/Jupyter/kernels/ir
  julia-1.1            /Users/Peezy/Library/Jupyter/kernels/julia-1.1
  python2              /Users/Peezy/Library/Jupyter/kernels/python2
  python3              /Users/Peezy/Library/Jupyter/kernels/python3
  wolframlanguage12    /Users/Peezy/Library/Jupyter/kernels/wolframlanguage12
```
It would be really appreciated if anyone could provide some advice.

**Comment by cc-wr** [comment]
It appears that `Hydrogen`'s "language mappings" require the use of the `language` field in a kernel's `JSON` configuration to refer to a kernel. (See the section below for more information, if needed.)

By default, `WolframLanguageForJupyter` uses  "Wolfram Language" as its value for this setting. However, `Hydrogen` seems to expect that the `language` value be entirely lowercase, so try using "wolfram language" (all lowercase) in a `{"wolfram language": "Mathematica"}` mapping.

**I would like to note, however, that `WolframLanguageForJupyter` is not yet designed to integrate well with `Atom` and `Hydrogen`, so the result may not be adequate for your purposes.**

---

Jupyter kernels are specified according to a `JSON` configuration. You can see the `JSON` configurations for your installed kernels by running `jupyter kernelspec list --json` in your system's shell.

For example, on my system, this command generates the following output (with arrows pointing to `language` fields).

```
{
  "kernelspecs": {
    "wolframlanguage12": {
      "resource_dir": "/Users/cc-wr/Library/Jupyter/kernels/wolframlanguage12",
      "spec": {
        "argv": [
          "/Applications/Mathematica.app/Contents/MacOS/WolframKernel",
          "-script",
          "/Users/cc-wr/WolframLanguageForJupyter/WolframLanguageForJupyter/Resources/KernelForWolframLanguageForJupyter.wl",
          "{connection_file}",
          "ScriptInstall"
        ],
        "env": {},
        "display_name": "Wolfram Language 12",
        "language": "Wolfram Language", [<---]
        "interrupt_mode": "signal",
        "metadata": {}
      }
    },
    "python3": {
      "resource_dir": "/Users/cc-wr/anaconda3/share/jupyter/kernels/python3",
      "spec": {
        "argv": [
          "/Users/cc-wr/anaconda3/bin/python",
          "-m",
          "ipykernel_launcher",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "Python 3",
        "language": "python", [<---]
        "interrupt_mode": "signal",
        "metadata": {}
      }
    }
  }
}
```

**Comment by paulps2** [comment]
Thanks for your reply and your detailed explanation.

Setting language mapping to `{"wolfram language": "Mathematica"}` still gives me the error `No kernel for grammar Mathematica found`. However, if I use `{"wolfram language": "mathematica"}`, the error disappears, but a simple `Print["Hello world!"]` won't return anything. It seems that the kernel didn't start. It's probably like what you said, WolframLanguageForJupyter is not yet designed to integrate well with Atom and Hydrogen.

**Comment by cc-wr** [comment]
I cannot reproduce this issue.

This is what I get when I run `Print["Hello world!"]`:

![hydrogen-with-wl](https://user-images.githubusercontent.com/47033353/62562199-b418e100-b84e-11e9-8395-025b98974a3d.png)

These are my `Atom` and `Hydrogen` package settings:

![hydrogen-with-wl3](https://user-images.githubusercontent.com/47033353/62562318-e0ccf880-b84e-11e9-8e23-38c318842006.png)

![hydrogen-with-wl3](https://user-images.githubusercontent.com/47033353/62562331-eaeef700-b84e-11e9-87a3-b0589087a59f.png)

**Comment by paulps2** [comment]
I used the same setting and now I have another error.

```
[IPKernelApp] ERROR | Invalid Message Traceback (most recent call last): File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 234, in dispatch_shell msg = self.session.deserialize(msg, content=True, copy=False) File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py", line 923, in deserialize raise ValueError("Invalid Signature: %r" % signature) ValueError: Invalid Signature: b'181b41f0c88bbcbae46c3dd2e1c6a8194e3e472f8ffc76a201a7b353a830aed7'
```

**Comment by paulps2** [comment]
Using python `print('Hello world!')` seems to be working
<img width="1439" alt="Screen Shot 2019-08-06 at 20 21 18" src="https://user-images.githubusercontent.com/16058003/62565810-ded35b80-b887-11e9-8bd1-c9f57891280d.png">

<img width="1439" alt="Screen Shot 2019-08-06 at 20 21 34" src="https://user-images.githubusercontent.com/16058003/62565818-e430a600-b887-11e9-9d1a-4703e2b76bd6.png">

**Comment by paulps2** [comment]
Reinstall the Paclet resolves the issue
