### ISSUE TITLE
Support for Jupyter-console

### ISSUE THREAD

**Issue by vegerot** [WolframResearch/WolframLanguageForJupyter#65]
Currently `jupyter-console --kernel=wolframlanguage12` does not display output without `Print`
e.g. `1+1` does not print anything.  You need to do `Print[1+1]` to see output, even though `1+1` would suffice in a Jupyter notebook

Similar to how I run `jupyter-console` instead of `python` when I want a Python repl because iPython is generally better than python, having `jupyter-console --kernel=wolframlanguage12` would be a better alternative to `wolframscript` from the Terminal

**Comment by cc-wr** [comment]
Does #68 resolve this for you?

**Comment by vegerot** [comment]
Perfect.  Thank you

**Comment by vegerot** [comment]
Just one small thing: sending `Exit[]` doesn't quit jupyter, just breaks it.  `^d` does work however, and that's a really easy workaround.

To quit regular `python`, `exit` doesn't work, you need to do `exit()`, but in `jupyter-console` you can just type `exit` and it'll quit.

**Comment by cc-wr** [comment]
> Just one small thing: sending `Exit[]` doesn't quit jupyter, just breaks it. `^d` does work however, and that's a really easy workaround.
>
> To quit regular `python`, `exit` doesn't work, you need to do `exit()`, but in `jupyter-console` you can just type `exit` and it'll quit.

@vegerot, do the recent commits in #68 resolve this for you? `Exit[]` and `exit` should now end a `jupyter-console` session.

**Comment by vegerot** [comment]
[👌](https://i.kym-cdn.com/photos/images/newsfeed/001/168/676/09e.gif)

**Comment by cc-wr** [comment]
A general request for comments on the pull request for addressing this issue, #68, is at #72.
