### ISSUE TITLE
Request For Comments: Add jupyter-console support

### ISSUE THREAD

**Issue by cc-wr** [WolframResearch/WolframLanguageForJupyter#72]
This a "Request For Comments/Consensus"-type issue for the pull request #68 ("Add jupyter-console support").

The commits contained in this pull request are:

* Add jupyter-console support, and add redirection of Wolfram Language messages during the execution of an input
* Add support for ending a jupyter-console session when Quit[\_\_\_] or Exit[_\_\_] are evaluated, or when the code strings "Quit", "Exit", "quit", or "exit" exactly are sent over by the console
* Do not allow the evaluation of the exit code strings (i.e., "Quit", "Exit", "quit", and "exit")
* Limit the Quit[] and Exit[] redefinition to the arguments that the actual Quit[] and Exit[] can take

---

Any relevant comments (e.g., support, complaints, objections, suggested improvements) are welcome.

It may also be helpful if you provide something like the following in your comment:

> * +2 : I am happy with this proposal, and I will argue for it
> * +1 : I am happy with this proposal, but will not argue for it
> * 0 : I have no opinion
> * -1 : I am not happy with this proposal, but will not argue against it
> * -2 : I am not happy with this proposal, and I will argue against it

https://xenproject.org/developers/governance/#expressingopinion

---

This request ends in one week.

**Comment by vegerot** [comment]
+2: I think this is great.  Fits in line with what the other jupyter kernels currently do.   And just adds functionality without removing anything

**Comment by cc-wr** [comment]
Since no comments against this request were registered, I will go ahead and merge #68.
