### ISSUE TITLE
Exponent in output

### ISSUE THREAD

**Issue by vipa7070** [WolframResearch/WolframLanguageForJupyter#74]
Some issue with exponents in the output.
Try for example:
`n=5.*10^12;`
`n*Range[20]`

**Comment by cc-wr** [comment]
Does #75 resolve this for you?

You can control where the line breaks occur in the output by using different values for `width` in a command like `SetOptions[$Output, PageWidth->width]`.

**Comment by vipa7070** [comment]
In my case this don't seem to solve the problems. The output isn't a string, it's a copiable text.
![immagine](https://user-images.githubusercontent.com/46306351/71356304-16664a00-2582-11ea-8ced-e1adbbeef829.png)

**Comment by cc-wr** [comment]
Are you trying this under #75?

Using `SetOptions` requires #75, as it allows you to adjust the result #75 achieves.

**Comment by cc-wr** [comment]
@vipa7070, see my comment above:

> Are you trying this under #75?
>
> The above `SetOptions` command requires #75, since it allows you to adjust the result #75 achieves.

**Comment by vipa7070** [comment]
I've try `SetOptions[$SetOutput, PageWidth->75]`
I've some problem for trying #75 at the moment.
Could you post an image of your result under #75 of my previous example.
I think (but I'm not sure) that the correct result should look like at what I get if I add `StandardForm`.
![immagine](https://user-images.githubusercontent.com/46306351/72611080-6938e480-3929-11ea-8109-15f749263c0b.png)

**Comment by cc-wr** [comment]
The following is my result under #75.

![pull-request-75-example](https://user-images.githubusercontent.com/47033353/72633371-4e18a580-3926-11ea-9461-88e5c04da606.png)

**Comment by cc-wr** [comment]
@vipa7070, did the above screenshot help at all?

**Comment by vipa7070** [comment]
I don't have try on my system, but I think the problem is solved. Thanks for your work on this problem and for this project.

**Comment by cc-wr** [comment]
A general request for comments on the pull request that should address this issue, #75, is at #48.

**Comment by cc-wr** [comment]
This issue should be resolved in `master`.
