### ISSUE TITLE
TeXForm Output in JupyterLab

### ISSUE THREAD

**Issue by PhyX-Meow** [WolframResearch/WolframLanguageForJupyter#83]
Hello, I am using Jupyterlab, and I found that if use TeXForm[] for the cell output, it looks just great.

![Snipaste_2020-03-05_13-59-54](https://user-images.githubusercontent.com/17513581/75952452-bc6ef280-5ee9-11ea-91f5-584d7b7518ee.png)
![Snipaste_2020-03-05_14-00-44](https://user-images.githubusercontent.com/17513581/75952456-c0027980-5ee9-11ea-997e-47cdf2da4fe9.png)

I guess it's because jupyter lab automatically renders the tex expressions.

However there's still some ploblem with this method.
If the output expression is too long, something bad happens.
Here's a short code in my homework:
`f[z_] := (z + I)/(I*z + 1);x = Re@f@a; y = Im@f@a;xi = f@Exp[I theta];
FullSimplify[y / ((x - xi)^2 + y^2) * f'@Exp[I theta]]`

it should output someting like this
![Snipaste_2020-03-05_14-10-48](https://user-images.githubusercontent.com/17513581/75952956-2045eb00-5eeb-11ea-9807-1d1d52aa7f03.png)
But actually it looks like this
![Snipaste_2020-03-05_14-12-13](https://user-images.githubusercontent.com/17513581/75953036-55523d80-5eeb-11ea-8c9c-69731c7b4246.png)
An unexpected '>' in the expression
I turn to the source file of this notebook and found
![Snipaste_2020-03-05_14-15-33](https://user-images.githubusercontent.com/17513581/75953180-cbef3b00-5eeb-11ea-9407-12cd1a1e698e.png)
It seems the '>' occurs when the output wrap to a new line.
I tried in my shell and get the same wrap.

My question is, is there any method to get the right result or simplily disable the line warpping

**Comment by PhyX-Meow** [comment]
Thanks Everyone!

**Comment by jfultz** [comment]
I'm not set up with the Jupyter+Wolfram kernel to test this right now, but in Wolfram Language, one would typically solve line-wrapping problems like this by doing:
```
SetOptions["stdout",PageWidth->Infinity]
```
It certainly works to stop the WL language from imposing line-wrapping onto `TeXForm` output on the command-line, and I suspect it'll work similarly in Jupyter, unless the WL plugin overrides your change (which it might in some circumstances).

You might be interested to know that you can also set the default `FormatType` to `TeXForm` by doing something similar:
```
SetOptions["stdout",FormatType->TeXForm]
```
But I don't think most people would appreciate this as a default.  This would, for example, deeply break default graphics output.

**Comment by PhyX-Meow** [comment]
@jfultz Thanks, it works, but in a strange way.
I tried pagewidth infinity but nothing changed.
Then I tried a small pagewidth and get more '>' in the expression
Finally I tried a large pagewidth but not infnity (such as 200), and get the right output.
It looks really strange, seems the infinity pagewidth is not processed correctly?

**Comment by arnoudbuzing** [comment]
Note that the Wolfram Language is case-sensitive.

So `pagewidth->infinity` is meaningless. It should be `PageWidth->Infinity`.

**Comment by PhyX-Meow** [comment]
@arnoudbuzing I know it. I just use the lowercase in the comment for convenience, or I would have experienced an error from wolfram kernel

**Comment by cc-wr** [comment]
@PhyX-Meow, sorry, this is a bug. `WolframLanguageForJupyter` should not be inserting line breaks in `text/html` results that contain TeX source, and `WolframLanguageForJupyter` should not be rejecting `Infinity` as a page width. #84 should resolve both of these issues.

With #84, line breaks in `text/html` results that contain TeX source are now disallowed, and you should not have to run `SetOptions["stdout", PageWidth -> Infinity]` for this purpose.

**Comment by glennhanks** [comment]
One more problem: `ToExpression[" \\frac{1}{2}  "`, TeXForm] does not work. According to the source of ipynb, it shows:    
`"source": [
    "ToExpression[\" \\\\frac{1}{2}  \", TeXForm]"
   ]`

**Comment by cc-wr** [comment]
> One more problem: `ToExpression[" \\frac{1}{2} ", TeXForm]` does not work. According to the source of ipynb, it shows:
> `"source": [ "ToExpression[\" \\\\frac{1}{2} \", TeXForm]" ]`

@glennhanks, this is a separate issue that the pull request #102 attempts to address.

**Comment by cc-wr** [comment]
A general request for comments on the pull request #84 (which addresses @PhyX-Meow's issue) and the pull request #102 (which should address @glennhanks' issue) is at #103.
