### ISSUE TITLE
Can't call Julia from Notebook

### ISSUE THREAD

**Issue by freemin7** [WolframResearch/WolframLanguageForJupyter#86]
I installed the latest version of Wolfram Engine today and set up Notebook support. The notebook works fine but certain features of the Wolfram language are not available.
`$VersionNumber` yields 12.
```(v1.3) pkg> st
    Status `~/.julia/environments/v1.3/Project.toml`
  [c52e3926] Atom v0.12.10
  [6e4b80f9] BenchmarkTools v0.5.0
  [a134a8b2] BlackBoxOptim v0.5.0 [`~/.julia/dev/BlackBoxOptim`]
  [a6e380b2] ControlSystems v0.5.3
  [864edb3b] DataStructures v0.17.12
  [0c46a032] DifferentialEquations v6.13.0
  [fa6b7ba4] DualNumbers v0.6.2
  [26cc04aa] FiniteDifferences v0.9.5
  [682c06a0] JSON v0.21.0
  [e5e0dc1b] Juno v0.8.1
  [d4b2101a] Lint v0.0.0 #master (https://github.com/tonyhffong/Lint.jl)
  [18c93696] MathLink v0.1.1
  [65888b18] ParameterizedFunctions v5.2.0
  [d96e819e] Parameters v0.12.0
  [91a5bcdd] Plots v1.0.9
  [c3e4b0f8] Pluto v0.6.1
  [295af30f] Revise v2.6.0
  [366cf18f] RigidBodyDynamics v2.2.0
  [e61f16d8] RigidBodySim v1.3.0
  [90137ffa] StaticArrays v0.12.1
  [c79d492b] TrajectoryOptimization v0.1.2
  [c2297ded] ZMQ v1.2.0
```
This means ZMQ and JSON are installed.

However
`ExternalEvaluate["Julia", "Dict(\"one\" => 1, \"two\" => 2, \"three\" \
=> 3)"]`
`session = StartExternalSession["Julia"]`
`FindExternalEvaluators["Julia"]`
All fail with the error:
``` `1` is not a known system in the ExternalEvaluate Framework.: Julia is not a known system in the ExternalEvaluate Framework.```

This feature is meant to be available on version 12 as by [https://reference.wolfram.com/language/ref/ExternalEvaluate.html](https://reference.wolfram.com/language/ref/ExternalEvaluate.html)

Any ideas?

**Comment by cc-wr** [comment]
@freemin7,

(I apologize for the delay.)

I do not think `"Julia"` was a known system in the ExternalEvaluate Framework in version 12.

Note that https://reference.wolfram.com/language/ref/externalevaluationsystem/Julia.html states (presumably that Julia support is) "NEW IN 12.1."

**Comment by freemin7** [comment]
Thanks ... you are right. Sorry.
