### ISSUE TITLE
InputForm not pastable: it inserts ">" for long expressions

### ISSUE THREAD

**Issue by tueda** [WolframResearch/WolframLanguageForJupyter#93]
It would be nice if `InputForm` could output copyable and *pastable* text representation within the valid Wolfram language syntax, even for long expressions. Currently, I get `>` for each line break, which is not good to paste to another place:

![image](https://user-images.githubusercontent.com/1481665/87852345-1c67b200-c93c-11ea-9b31-1ccfc237320f.png)

Edit: indeed, it would be really good if `InputForm` could give the textual output as in a terminal, without any extra line breaks between lines: 
```
In[1]:= (1 + x)^20 // Expand // InputForm

Out[1]//InputForm=
1 + 20*x + 190*x^2 + 1140*x^3 + 4845*x^4 + 15504*x^5 + 38760*x^6 + 77520*x^7 +
 125970*x^8 + 167960*x^9 + 184756*x^10 + 167960*x^11 + 125970*x^12 +
 77520*x^13 + 38760*x^14 + 15504*x^15 + 4845*x^16 + 1140*x^17 + 190*x^18 +
 20*x^19 + x^20
```

**Comment by arnoudbuzing** [comment]
You may get better results if you evaluate this first: `SetOptions[$Output, PageWidth -> Infinity]`

(I did not verify this in Jupyter, but it might help you)

**Comment by tueda** [comment]
Thanks for the comment, but it doesn't seem to work in Jupyter:
![image](https://user-images.githubusercontent.com/1481665/87943607-3c80a800-cad9-11ea-9421-2b3bde326a77.png)

**Comment by cc-wr** [comment]
@tueda, the pull request #84 should make it so that `SetOptions[$Output, PageWidth -> Infinity]` works for Wolfram Language for Jupyter, such that evaluating it removes the line breaks you have seen for long expression results.

**Comment by cc-wr** [comment]
There is a general request for comments on the pull request #84, which should address this issue, at #103.
