### ISSUE TITLE
"pcilib:  Cannot open /proc/bus/pci" on Ubuntu on WSL (e.g. Plot3D)

### ISSUE THREAD

**Issue by NicoJG** [WolframResearch/WolframLanguageForJupyter#94]
I'm trying to get "Wolfram Language For Jupyter" running on WSL 2 (Windows Subsystem for Linux)
I'm running Ubuntu 18.04.
I installed Anaconda in it, then Wolfram Engine and the Wolfram Language For Jupyter.
At first the Kernel wouldn't run, I had to do 2 things:
- Install libasound2
- Install VcXsrv in Windows because I got: `Qt issued a critical error: Could not connect to any X display.`

By that I got the Jupyter Notebook running.

But it seems something is still missing/not working. 
Because I get the main error: `pcilib: Cannot open /proc/bus/pci`
Trying to use Plot3D will fail:

![Wolfram-Jupyter-Fail](https://user-images.githubusercontent.com/55792255/89352193-dc325e80-d6b3-11ea-939e-c33489f20aa0.png)

I tried running it with `sudo jupyter notebook`, but I get the error: `sudo: jupyter: command not found`.

**Comment by cc-wr** [comment]
We do not have a supported/established workflow for WSL.

However, https://github.com/microsoft/WSL/issues/327 and https://devblogs.microsoft.com/commandline/the-windows-subsystem-for-linux-build-2020-summary/#wsl-gpu may be relevant to this effort.
