### ISSUE TITLE
Echo does not work

### ISSUE THREAD

**Issue by stone-zeng** [WolframResearch/WolframLanguageForJupyter#95]
In a Mathematica frontend, `Echo` will lead to a printed message and an output, while the `;` will suppress the output. However, when I use the following code in a jupyter notebook:

```wl
Echo[1+1]
```

It gives an output `2`, which is as predicted.

But when I add a semicolon:

```wl
Echo[1+1];
```

There will be no output then.

- Wolfram language version: 12.0.0 for Linux x86 (64-bit) (April 7, 2019)
- Operation system: Linux x86 (64-bit)
- Jupyter version:
    - jupyter core: 4.6.3
    - jupyter-notebook: 6.0.3
    - qtconsole: not installed
    - ipython: 7.13.0
    - ipykernel: 5.2.0
    - jupyter client: 6.1.2
    - jupyter lab: not installed
    - nbconvert: 5.6.1
    - ipywidgets: 6.0.0
    - nbformat: 5.0.4
    - traitlets: 4.3.3

**Comment by cc-wr** [comment]
The pull request #104 should fix this issue.

**Comment by cc-wr** [comment]
A general request for comments on the pull request #104, which addresses this issue, is at #105.
