### ISSUE TITLE
/WolframKernel: No such file or directory

### ISSUE THREAD

**Issue by stephenhky** [WolframResearch/WolframLanguageForJupyter#96]
I am trying to using Wolfram Engine on Jupyter Notebook. I already have Anaconda, and my Jupyter is working well with Python and Julia right now. I installed Wolfram Engine, and I activated it with my license. It is running too. However, somehow my `wolframscript` does not work, but from the REAME here, it is not necessary. I cloned this repository, and when I enter `./configure-jupyter.wls add`, it said:

`sh: /WolframKernel: No such file or directory`

and then it freezes. Is there anyway to fix it?

I am using macOS Catalina.

**Comment by jstin** [comment]
I ran into the same issue. As a quick workaround you can try running (assuming your install directly matches):

```
/Applications/Wolfram\ Engine.app/Contents/Resources/Wolfram\ Player.app/Contents/MacOS/wolframscript ./configure-jupyter.wls add
```

**Comment by stephenhky** [comment]
THanks! It works!
It looks like having the symbolic link elsewhere would cause the error message.
