### ISSUE TITLE
Kernel shutdown when importing onnx model

### ISSUE THREAD

**Issue by luyuwuli** [WolframResearch/WolframLanguageForJupyter#98]
Take the [GoogleNet](https://github.com/onnx/models/tree/master/vision/classification/inception_and_googlenet/googlenet)
as an example.
When I try to import it 

`gNet=Import["googlenet-3.onnx"];`

the kernel shutdown.
Although I could import it in the `wolfram` prompt without any problem.

(Mathematica v12.1.1 and Debian 10 x64)

**Comment by cc-wr** [comment]
This is presumably related to #87, specifically https://github.com/WolframResearch/WolframLanguageForJupyter/issues/87#issuecomment-647707013.

**Comment by cc-wr** [comment]
@luyuwuli, can you still reproduce this issue?

**Comment by luyuwuli** [comment]
After reading your #87 comment, 
I can confirm that Windows is free from this issue, and I can bypass the issue by removing the folder `/usr/local/Wolfram/Mathematica/12.1/SystemFiles/Components/MXNetLink` 
(defenitely not the recommended way to uninstall the paclet, but I can still load it again without any problem)

**Comment by cc-wr** [comment]
@luyuwuli, can this issue be closed?

**Comment by luyuwuli** [comment]
Yes, sorry for the delay.
